rvm:
  - 2.2.4
before_script:
  - psql -c 'create database workshops_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load
addons:
  postgresql: '9.3'
